### PR TITLE
letters in front of plots – matplotlib

### PR DESCRIPTION
**Pull request by mullimanko**
Add an explanation of the letters in front of multiple matplotlib plots. See: https://github.com/holoviz/holoviews/issues/4773

### CODE REVIEW

**Comment by philippjfr** [comment]
@mullimanko This is a good start thanks. Could you maybe expand the docs a little bit with a small section about subplot labels. Something like:

```
### Subplot Labels

The matplotlib backend enables subplot labels by default which make it easy to refer to individual plots. You can switch the enumeration between uppercase, lowercase, numeric and roman numerals by setting the `sublabel_format` option to one of `'{Alpha}'`, `'{alpha}'`, `'{numeric}'` or `'{roman}'` respectively. If you want to disable subplot labels entirely set `sublabel_format=''`.

**Comment by philippjfr** [comment]
@mullimanko Any chance you've got a minute to apply the change?

**Comment by mullimanko** [comment]
Sure, sorry, I am a github newbie, I just have to find out what to do. I'll guess I have to look in the github guide.

**Comment by philippjfr** [comment]
All you should have to do is take the snippet above, add it to the notebook and then commit the new changes. Let me know if I can help you with that. If you run into trouble I can probably apply the changes to this PR myself.

**Comment by philippjfr** [comment]
Thanks for your contribution!

**Comment by jlstevens** [comment]
Yes, thanks for clarifying things for other users!

**Pull request merged**
