### PR TITLE
Remove bokeh from install instructions (Fix #5547)

### LINKED ISSUE #5547: Docs: Install instructions for holoviews don't work correctly with new libmamba solver
#### ALL software version info
[Documentation on installation](https://github.com/holoviz/holoviews#installation).  This looks like an issue with the libmamba solver so should also be asked about / logged in `conda`. But using `conda install -c pyviz holoviews` is sufficient and works consistently; however, `conda install -c holoviews bokeh` does not.

#### Description of expected behavior and the observed behavior

It seems `conda install -c pyviz holoviews` installs the correct bokeh dependency. I don't know why we need to install `bokeh` separately; although I would expect `conda install -c pyviz holoviews bokeh` and `conda install -c pyviz holoviews` to install the same set of packages. I'll also raise this issue in the conda channel. I think this is related to the libmamba solver. If I use the classic solver, I get the correct version of bokeh (2.4.3). But I couldn't fully test since `python -c 'import holoview'` raised a linkage issue when using the classic solver - haven't dug into that yet.

```
% conda create -n hv_test -c pyviz holoviews bokeh
conda list -n hv_test 'bokeh|holoviews|panel'
# packages in environment at /Users/jasmine/miniconda3/envs/hv_test:
#
# Name                    Version                   Build  Channel
bokeh                     3.0.2           py310hca03da5_0    defaults
holoviews                 1.14.9                     py_0    pyviz
panel                     0.10.3                     py_0    pyviz
```

Compare this to only installing the holoviews package with the libmamba solver which installs correct bokeh version:

```
% conda create -n only_hv -c pyviz holoviews
% conda list -n only_hv 'bokeh|holoviews|panel'
# packages in environment at /Users/jasmine/miniconda3/envs/only_hv:
#
# Name                    Version                   Build  Channel
bokeh                     2.4.3           py310hca03da5_0    defaults
holoviews                 1.15.2                     py_0    pyviz
panel                     0.14.1                     py_0    pyviz
```

#### Complete, minimal, self-contained example code that reproduces the issue

```

# this breaks when using the libmamba solver since that installs latest bokeh dependency
conda create -n hv -c pyviz holoviews bokeh

# this works with the libmamba solver since it installs bokeh version 2.4.3
conda create -n hv -c pyviz holoviews

```

#### Stack traceback and/or browser JavaScript console output

```
% conda create -n hv -c pyviz holoviews
% conda activate hv
% python -c 'import holoviews'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/holoviews/__init__.py", line 12, in <module>
    from .annotators import annotate                         # noqa (API import)
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/holoviews/annotators.py", line 10, in <module>
    from panel.pane import PaneBase
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/__init__.py", line 3, in <module>
    from . import layout # noqa
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/layout/__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/layout/accordion.py", line 5, in <module>
    from .base import NamedListPanel
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/layout/base.py", line 13, in <module>
    from ..io.model import hold
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/io/__init__.py", line 8, in <module>
    from ..config import config
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/config.py", line 20, in <module>
    from .io.notebook import load_notebook
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/io/notebook.py", line 40, in <module>
    from .embed import embed_state
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/io/embed.py", line 20, in <module>
    from .model import add_to_doc, diff
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/io/model.py", line 11, in <module>
    from bokeh.models import Box, ColumnDataSource, Model
ImportError: cannot import name 'Box' from 'bokeh.models' (/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/bokeh/models/__init__.py)
```

### PR DESCRIPTION
**Pull request by sandhujasmine**
Very small change to fix https://github.com/holoviz/holoviews/issues/5547
Let `bokeh` get installed as a dependency of the `panel` library

### CODE REVIEW

**Comment by maximlt** [comment]
Hi @sandhujasmine ! :)

Actually, I'm not sure I actually knew this page existed (https://holoviews.org/index.html#installation). It's linked from the landing page, which itself has an install section (https://holoviews.org/index.html#installation). Both are outdated, the former says that HoloViews' minimal install come with Param, Numpy and Pandas only, while it's in practice a little more (see below), while the later says that Python 2.7 is no longer supported. Not to mention the README.md file that also has installation instructions 🙃 

```
# from setup.py
    "param >=1.9.3,<2.0",
    "numpy >=1.0",
    "pyviz_comms >=0.7.4",
    "panel >=0.13.1",
    "colorcet",
    "packaging",
    "pandas >=0.20.0",
```

Panel no longer has install instructions on its landing page but in the *Install* page of its getting started. Same for hvPlot and Lumen, following that trend. I think we should do the same for HoloViews, i.e. the first page users going through the getting started guide would be the (updated) install page. What do you think @droumis ?

On the particular issue you're trying to solve, here is some context. I think HoloViews was designed to work without any plotting backend and its runtime dependencies don't include bokeh/matplotlib/plotly. Bokeh happens to always be installed now as it's a dependency of Panel. One could argue that Bokeh could become a default *official* backend, that's always installed (even if Panel would no longer depend on it), but that's an entirely other discussion.

I think that to give a sense to users that they do need to install the plotting backend(s) they want to use (e.g. `conda install holoviews matplotlib`) it's best for now to keep `conda install holoviews bokeh` in the install instructions. However, to fix the issue you reported I'd suggest replacing it by `conda install holoviews "bokeh <3"`.

Just noting something else, we have observed that with conda-libmamba-solver you don't always get the same solve. I'm not sure it applies here. But now you'll be less surprised if you observe that!

**Comment by sandhujasmine** [comment]
Thank you for the additional context @maximlt 

I've updated the PR to limit the 'bokeh <3' version. Fixing the version of `bokeh` in older versions of holoviews will fix as well so maybe unnecessary after that.
It also appears we need a larger update to the holoviews docs. 
Even though `bokeh` is a dependency from `panel`, holoviews can still have other plotting backends for other parts of its functionality. I'll educate myself more on this and happy to contribute to the docs if I can!

**Comment by jlstevens** [comment]
Thanks for the PR!

We had a discussion about this and I think we decided to drop `bokeh` from the install instructions. I'm happy to take it from here.

**Comment by jlstevens** [comment]
In order to avoid working from a fork, this PR is now superseded by #5562 

Thanks @sandhujasmine for getting the ball rolling!

**Pull request closed without merging**
