### PR TITLE
Updated badges in README.md

### PR DESCRIPTION
**Pull request by jlstevens**
Updated badges to point to GitHub Actions, not Travis.

### CODE REVIEW

**Comment by jlstevens** [comment]
Merging as this is a simple docs change that doesn't need tests to run. Happy to make another PR if @jbednar or @philippjfr feel these new badges can be further improved somehow.

**Comment by philippjfr** [comment]
What about the website?

**Comment by jlstevens** [comment]
You mean these badges or something else?

image

The badges above aren't about testing/CI.

**Comment by philippjfr** [comment]
Would expect testing badges to appear there and we should either drop or update the coverage one.

**Pull request merged**
