### PR TITLE
Support xyzservices.TileProvider as hv.Tiles input

### PR DESCRIPTION
**Pull request by martinfleis**
Implements suggestion 1) from #5057.

Bokeh and Plotly backends now support `xyzservices.TileProvider` as input for `hv.Plot`:

```py
import xyzservices.providers as xyz

hv.Tiles(xyz.CartoDB.Positron)
```

I have not added tests for the Bokeh backend as I have no idea where it should be. Can you point me to the right direction?

I'll add the same to GeoViews once this gets reviewed and we agree on specifics of the support.

### CODE REVIEW

**Comment by philippjfr** [comment]
This is great, thanks so much! There should probably be a `holoviews/tests/plotting/bokeh/test_tiles.py`. Happy to add the scaffolding for that or you can just copy the rough structure in one of the `test_{element}.py` files in the same directory.

**Comment by jlstevens** [comment]
Thanks for the contribution!

Hopefully we can get the tests on master working again at which point this PR can be rebased and merged.

**Comment by jlstevens** [comment]
Sorry for not getting back to this sooner!

Seems like your last commit didn't trigger the tests. Could you push another commit to see if the tests run this time? Alternatively, you could do another rebase against latest master...

**Comment by martinfleis** [comment]
Seems to work now. Awaiting approval.

**Comment by jlstevens** [comment]
Approved. I'm ready to merge assuming the tests go green. Do you agree @philippjfr ?

**Comment by martinfleis** [comment]
The new tests are all skipped in CI since xyzservices are not in any of envs. As I said above

> We should also add xyzservices to CI envs but I am not certain how that works in here. xyzservices requres Python 3.7 so adding it to setup.py as you do with other deps would probably break your 3.6-based tests.

**Comment by jlstevens** [comment]
The  `xyzservices` package on`conda-forge` is a noarch package and I successfully installed it into a conda 3.6 environment. It looks like the issue with 3.6 is on import (`from __future__ import annotations`) so what might work is to install `xyzservices` into the CI env across python versions and these specific tests can check for `python > 3.6` before importing `xyzservices` inline to run. Does that make sense?

**Comment by jlstevens** [comment]
Note that if you rebase again, the windows tests should pass. It would be nice to get these tests running on CI for Python > 3.6 so I won't merge just yet. @philippjfr Any opinions on whether it is ok to install `xyzservices` but make the tests conditional on the Python version?

**Comment by jlstevens** [comment]
@philippjfr At this point I would be happy to just merge. Do you agree?

**Comment by philippjfr** [comment]
The 3.6 test failures are unrelated and otherwise this is passing. So I'll close.

**Pull request merged**
