### PR TITLE
Handle unsigned integer dtype in datashader aggregate operation

### PR DESCRIPTION
**Pull request by Hoxbro**
Fixes https://github.com/holoviz/hvplot/issues/670

<s>Still need to make tests.</s>

### CODE REVIEW

**Comment by jbednar** [comment]
Thanks, @Hoxbro ! Looks like a very reasonable fix to me, but I can't tell why the tests are failiing.

**Comment by Hoxbro** [comment]
I was wondering if I should add a check that raises an error if an uint64 array has values higher than 2 ** 64 // 2 - 1. 
Alternatively could be not accepting uint64 as a dtype. What are your thoughts on this?

**Comment by jbednar** [comment]
I'm happy to simply fail for uint64; without proper plumbing all the way through there's no way that could work reliably without checking all the data, and checking all the data seems slow, so better just to leave it to the user to convert to a signed array if they want to plot that (or if they really want it, to put uint support in Datashader!).

**Comment by maximlt** [comment]
Looks good to me. @jbednar if you get the chance to review this I could include it in the next release.

**Review by jbednar — APPROVED** [review]

**Pull request merged**
