### PR TITLE
Fix datetime clipping on RangeXY stream

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes https://github.com/holoviz/holoviews/issues/5078

### CODE REVIEW

**Comment by jlstevens** [comment]
So the code to convert from timestamps was already there but being executed after the comparisons were already attempted? :-S

Happy to merge but I'll let you consider whether you think it is worth adding a unit test first.

**Comment by philippjfr** [comment]
>So the code to convert from timestamps was already there but being executed after the comparisons were already attempted? :-S

It was needed for other stuff, I didn't anticipate that x0 could be float but x1 be a datetime or vice versa.

**Comment by philippjfr** [comment]
>Happy to merge but I'll let you consider whether you think it is worth adding a unit test first.

Honestly don't have the bandwidth to keep plugging away at HV.

**Comment by jlstevens** [comment]
Ok then! Merging.

**Pull request merged**
