### PR TITLE
Refactor mpl deprecation handling

### PR DESCRIPTION
**Pull request by poplarShift**
Following discussions in #4335

### CODE REVIEW

**Comment by philippjfr** [comment]
Two flakes making the tests fail:

```
holoviews/plotting/mpl/plot.py:23:1: F401 '.util.mpl_version' imported but unused
holoviews/plotting/mpl/renderer.py:21:1: F401 '.util.mpl_version' imported but unused
```

**Comment by poplarShift** [comment]
There you go!

**Comment by philippjfr** [comment]
Thank you, will merge and tag 1.13.2 either tonight or tomorrow.

**Comment by poplarShift** [comment]
If it's not too late I just renamed the util function, had second thoughts about that :)

**Comment by philippjfr** [comment]
Not too late.

**Pull request merged**
