### PR TITLE
Allow subcoordinates to be drawn from NdOverlay dimensions

### PR DESCRIPTION
**Pull request by philippjfr**
Resolves https://github.com/holoviz/holoviews/issues/6028

### CODE REVIEW

**Comment by philippjfr** [comment]
This should be good to merge. I will investigate whether adding support for subcoordinate groups drawn from the NdOverlay dimensions makes sense as a separate PR.

**Review by hoxbro — APPROVED** [review]
Tests pass and look like a relatively simple change.

**Comment by droumis** [comment]
This doesn't seem to work for `subcoordinate_y` with the wide df example posted [here](https://github.com/holoviz/holoviews/issues/6260)

```python
df = pd.read_csv('https://datasets.holoviz.org/stocks/v1/stocks.csv', parse_dates=['Date']).set_index('Date')

hv.NdOverlay({col: hv.Curve(df, 'Date', (col, 'Price')).opts(tools=['hover'], subcoordinate_y=True) for col in df.columns}, 'Ticker')
```

image

**Comment by droumis** [comment]
If I zoom out, the lines appear, so looks like a ranging issue.

https://github.com/holoviz/holoviews/assets/6613202/e7173130-b3fe-4f63-8fb3-126911c62c92

**Comment by philippjfr** [comment]
Thanks, investigating.

**Pull request merged**
