### PR TITLE
flask-dashapp

### PR DESCRIPTION
**Pull request by lelatbones**
Here I added an example inside the user guide Deploying_Bokeh_Apps.ipynb where you can use the Bokeh Application that you create a Holoviews Dynamic Map in, and then serve that Application through a Flask Application.

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks a lot this will be super useful. Before I have a more detailed look I have two suggestions:

1. Would you mind clearing the notebook before committing it? We generally do not check in notebooks with output.
2. Would it make sense to add a standalone app in https://github.com/ioam/holoviews/tree/master/examples/gallery/apps/bokeh?

**Comment by lelatbones** [comment]
I do not mind doing step one, I have a standalone app in the link (here) which is underneath the embed.html in the steps block.

**Comment by lelatbones** [comment]
I could move the folder from my standalone app, and include it there if you prefer

**Comment by jlstevens** [comment]
Looks good! I'm happy to review this PR if it is ready at which point I would go ahead and clear out the remaining notebook metadata...

**Comment by lelatbones** [comment]
Alright, I think it's good to go. Thanks guys!

**Comment by jlstevens** [comment]
Quick note to say I'll review this PR this evening.

**Comment by jlstevens** [comment]
@lelatbones I'm really sorry about letting this PR languish without review. I'll definitely take a look this weekend!

**Comment by lelatbones** [comment]
That is ok, I'm in no rush, thank you!

**Comment by lelatbones** [comment]
Hey, I was wondering on the progress of merging this with master. Thanks!

**Comment by philippjfr** [comment]
Sorry, I'll take a look very soon. Several people have asked about this so this is definitely a priority and I'll probably use this to write a deployment guide for Panel as well.

**Comment by philippjfr** [comment]
Sorry this sat around forever, I'm just going to merge and perform any cleanup in a new PR.

**Pull request merged**
