### PR TITLE
 Support hit-tested group-wise wheel zoom renderers for subcoordinate_y

### PR DESCRIPTION
**Pull request by maximlt**
resolves https://github.com/holoviz/holoviews/issues/6268

By relying on https://github.com/bokeh/bokeh/pull/13826 to be released in Bokeh 3.5, that adds hit-testing properties to the wheel zoom tool. When building a *subcoordinate_y overlay with groups* which has a default wheel zoom tool, this tool is updated to enable hit-testing, with the `hline` mode (i.e. zooming is effective only when the mouse intersects horizontally with an element) and the `GroupByModels` behavior (i.e. zooming only affects a single group at a time).

Monosnap screencast 2024-06-18 17-11-04

### CODE REVIEW

**Comment by droumis** [comment]
ready for review?

**Comment by maximlt** [comment]
> ready for review?

I'd wait for Bokeh 3.5 to be released.

**Comment by droumis** [comment]
Bokeh 3.5 is released; ready to request a review?

**Comment by maximlt** [comment]
> Bokeh 3.5 is released; ready to request a review?

I have tested again this PR, not with Bokeh 3.5 but with 3.5rc1 as there's no dev release of Panel yet compatible with the final 3.5 release of Bokeh. It worked as expected. Ready for review.

**Review by droumis — APPROVED** [review]

**Comment by droumis** [comment]
ncie work!

**Comment by droumis** [comment]
tested with Panel 1.5.0b1 and Bokeh 3.5.0

**Pull request merged**
