### PR TITLE
Small improvements to vscode-notebook support

### PR DESCRIPTION
**Pull request by Hoxbro**
VScode notebook did not interactive work with a DynamicMap. 

It still does not fully work as `pn.config.comms` needs to be set to `vscode`. I think It would be nice if the comms was set by holoviews and not dependent on Panel, but I think this is out of scope for this PR.  

With `pn.config.comms = vscode`:

https://user-images.githubusercontent.com/19758978/185586615-4372d741-aabc-43a5-9a93-b442d59b2c68.mp4

With `pn.config.comms = default`:

https://user-images.githubusercontent.com/19758978/185586673-97a323bb-8c77-4712-a0c5-b6dfe9378da7.mp4

``` python
import holoviews as hv
import pandas as pd

hv.extension('bokeh')

import panel as pn
pn.config.comms = "vscode"  # <- this is needed for it to work

# creating a dataframe with both an int and an obj dtype
df = pd.DataFrame({
    'count':    [ 0,    1,    2 ], 
    'distance': [ 3,    4,    7 ],
    'length':   [ 5,  -20,   35 ]
})

# set up a DynamicMap where the user can select the y_axis column
y_dim = hv.Dimension('y_column', values=df.columns.tolist(), default='distance')

def return_scatter(col_name):
    return hv.Scatter(df, kdims='count', vdims=[col_name])

hv.DynamicMap(return_scatter, kdims=y_dim).opts(framewise=True, axiswise=True)
```

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks good, thanks @Hoxbro!

**Comment by boustrephon** [comment]
When I run the code from @Hoxbro , I get the following error. Have I failed to install something?

```
File ~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/holoviews/core/options.py:1405, in Store.render(cls, obj)
   1403 data, metadata = {}, {}
   1404 for hook in hooks:
-> 1405     ret = hook(obj)
   1406     if ret is None:
   1407         continue
...
--> 370     from jupyter_bokeh.widgets   import BokehModel
    371     from ..pane import panel
    372     model = panel(obj, **kwargs).get_root()

ModuleNotFoundError: No module named 'jupyter_bokeh'
:DynamicMap   [y_column]
```

**Comment by Hoxbro** [comment]
Try to download `jupyter_bokeh` either with conda or pip.

**Comment by boustrephon** [comment]
Thanks. I couldn't find it on `conda`, but it installed from `pip`...

```
File ~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/holoviews/core/options.py:1405, in Store.render(cls, obj)
   1403 data, metadata = {}, {}
   1404 for hook in hooks:
-> 1405     ret = hook(obj)
   1406     if ret is None:
   1407         continue
...
--> 430     return widget._repr_mimebundle()
    431 plaintext = repr(widget)
    432 if len(plaintext) > 110:

AttributeError: 'BokehModel' object has no attribute '_repr_mimebundle'
:DynamicMap   [y_column]
   :Scatter   [count]   (distance)
```

**Comment by boustrephon** [comment]
Thanks. The `anaconda` channel didn't have 1.15.4, but 1.15.3 worked anyway...

**Comment by Hoxbro** [comment]
Glad to hear :+1: 

> The anaconda channel didn't have 1.15.4, but 1.15.3 worked anyway...

Make sense 1.15.4 was released yesterday.

**Pull request merged**
