### PR TITLE
Ensure rangesupdate event fires on all plots with linked axes

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes https://github.com/holoviz/holoviews/issues/5381

### CODE REVIEW

**Comment by philippjfr** [comment]
Will push a fix later.

**Comment by jlstevens** [comment]
Odd, there is the [following error](https://github.com/holoviz/holoviews/actions/runs/3170329015/jobs/5162848607#step:10:255), but only on 3.9 ubuntu?!

```python
    def test_poly_edit_callback(self):
        polys = Polygons([[(0, 0), (2, 2), (4, 0)]])
        poly_edit = PolyEdit(source=polys)
        plot = bokeh_server_renderer.get_plot(polys)
>       self.assertIsInstance(plot.callbacks[0], PolyEditCallback)
E       AssertionError: <holoviews.plotting.bokeh.callbacks.PolyDrawCallback object at 0x7efd2eb31340> is not an instance of <class 'holoviews.plotting.bokeh.callbacks.PolyEditCallback'>
```

**Comment by philippjfr** [comment]
Nothing to do with this PR, has been a transient for over a year now.

**Comment by jlstevens** [comment]
I was wondering if it was a transient but I never realized we had one that was an `isinstance` check failing. Very weird!

Anyway, merging.

**Pull request merged**
