### PR TITLE
Support positional stream args in DynamicMap callback

### PR DESCRIPTION
**Pull request by jonmmease**
This PR is a step toward supporting #4433 using a `DynamicMap` transformation.  The idea is described in https://github.com/holoviz/holoviews/issues/4433#issuecomment-663715053.

## Background
The callback function for a `DynamicMap` is currently called by passing the kdim values as positional arguments, followed by stream parameter values as keyword arguments.  For example:

```python
import holoviews as hv
from holoviews.streams import Stream
XY = Stream.define('XY', x=0,y=0)
xy_stream = XY()

def callback_fn(i_value, y, x):
    ...

dmap = hv.DynamicMap(callback_fn, kdims=["i"], streams=[xy_stream])
```
Here the `i_value` argument is the `i` key dimension that is called positionally (named `i_value` to emphasize that it's called by position not by name), and the `x` and `y` arguments are the stream parameters and they are called as keyword arguments.  So here the `x` and `y` argument names must match the param names of the `xy_stream` stream.

This approach is convenient when writing callback functions by hand, when there are only a few stream parameters and the stream parameter names don't conflict. But it's less convenience when building a callback function programmatically that will input many streams with potentially overlapping parameter names. This will be the situation when building the transformation in #4433.

## Description
This PR adds a `positional_stream_args` parameter to the `DynamicMap` class that, when set to `True`, will configure the `DynamicMap` to pass stream values to the callback function positionally.  The stream arguments will follow the kdim arguments (if any), the value of each stream argument is a `dict` containing key-value pairs for each param in the stream, and the order of the stream arguments is determined by the order of the streams in the `streams` parameter list.

Here's an example of what this looks like:

```python
import holoviews as hv
from holoviews.streams import Stream
XY = Stream.define('XY', x=0,y=0)
xy_stream0 = XY()
xy_stream1 = XY()

def callback_fn(i_value, s0, s1):
    x0, y0 = s0['x'], s0['y']
    x1, y1 = s1['x'], s1['y']
    ...

dmap = hv.DynamicMap(
    callback_fn, kdims=["i"], streams=[xy_stream0, yx_stream1], positional_stream_args=True
)
```

When `positional_stream_args=True` there is no possibility of stream parameter name clashes.

Of course, the default is `False` to match the current behavior.

Does this sound reasonable @jlstevens @philippjfr ?

### CODE REVIEW

**Comment by philippjfr** [comment]
The changes look fine to me, but I'll try to fix the tests before merging.

**Comment by jonmmease** [comment]
Ok, updated with master and tests are passing. Anything else come to mind for this PR @philippjfr?

**Comment by jonmmease** [comment]
@philippjfr alright if we merge this today?

**Comment by philippjfr** [comment]
Yes, looks good to me.

**Comment by jonmmease** [comment]
Thanks a lot @philippjfr!

**Pull request merged**
