### PR TITLE
Fix imports for the multichan ts viewer demo

### PR DESCRIPTION
**Pull request by droumis**

### CODE REVIEW

**Review by maximlt — COMMENTED** [review]
Could you separate the imports from the code and put them above `Generating Data`, together with `hv.extension('bokeh')`. This seems to be like the other demos are structured, e.g.:

image

---

I re-ran the code for good measure and noticed there's a hover tool icon per curve in the toolbar. I don't remember seeing that before. I assume this is due to using the new `hover_tooltips` option? I guess it's not exactly the expected outcome.

image

**Comment by droumis** [comment]
> I re-ran the code for good measure and noticed there's a hover tool icon per curve in the toolbar. I don't remember seeing that before. I assume this is due to using the new hover_tooltips option? I guess it's not exactly the expected outcome.

Correct, I had opened an issue [here](https://github.com/holoviz/holoviews/issues/6252). At documented in that thread, the hover tools do get combined when it becomes a layout rather than an overlay.

**Comment by droumis** [comment]
using hv.Layout((curves_overlay, hv.Empty())) actually combines the hover tools, but I don't think we should be advertising this workaround

**Comment by droumis** [comment]
should be ready to merge. I'm guessing that the merging of the "subplot" tools within an overlay will be addressed another time, and otherwise should probably be default behavior for overlays, so there would be nothing to change further in this example.

**Comment by droumis** [comment]
In future versions, we should update to utilize the wide df mapper approach and NdOverlay instead of hv.Dataset and Overlay. But some issues need to be addressed when combining data from multiple groups with the wide df approach, so let's merge this for now.

**Pull request merged**
