### PR TITLE
Add support for non-categorical HeatMap

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes https://github.com/holoviz/holoviews/issues/2128

### CODE REVIEW

**Comment by jbednar** [comment]
Whoa, you're just going to throw this out here without any fanfare?  This is big news! What exactly has been done here?  Can we now have one numerical and one categorical axis?  Can categorical axis labels now be skipped when xticks is set?  Tell us more!

**Comment by philippjfr** [comment]
>Whoa, you're just going to throw this out here without any fanfare?

Still in progress :)

>Can we now have one numerical and one categorical axis?

Yes.

>Can categorical axis labels now be skipped when xticks is set?

Sadly no, might have a go at allowing that in bokeh though.

**Comment by philippjfr** [comment]
@jbednar I'm never quite decided about integers, sometimes you want to treat them as categorical other times you don't. Any opinion?

**Comment by philippjfr** [comment]
Here's the measles example in matplotlib and bokeh:

Screen Shot 2020-01-11 at 6 45 55 PM
Screen Shot 2020-01-11 at 6 46 26 PM

**Comment by philippjfr** [comment]
Okay I'm happy with this, I've disabled the xmarks and ymarks properties for regular HeatMaps and only support them when radial=True. They were quite confusing, very hairy to implement especially now that axes can be categorical OR numeric, and imo not all that useful. For a radial axis they basically replace grid marks and so are somewhat useful.

**Comment by jbednar** [comment]
That all sounds great.  I'd vote for treating integers as a numeric axis, since there is no ambiguity in labeling when skipping integer labels and numeric integer axes already support such skipping.  That example doesn't show how integer examples are handled right now; if the curve/error-bar plot were removed what would the axis look like?

**Comment by philippjfr** [comment]
>if the curve/error-bar plot were removed what would the axis look like?

The same.

**Pull request merged**
