### PR TITLE
To work around #6327

### PR DESCRIPTION
**Pull request by arafune**
While this PR is not still sufficient to work around #6327, such revision must be required at least.

The essential point of the change is the following part.

-            kdim_len = len(kdim_param.default) if kdims is None else len(kdims)
+            if kdims is None:
+                kdims = list(data.dims)
+            kdim_len = len(kdims)

While reading the code, I found the following part difficult to understand:
```python
if not isinstance(data, (xr.Dataset, xr.DataArray)):
```
To improve readability, I changed it to a more straightforward approach.  I hope you will accept this change as well.

### CODE REVIEW

**Comment by ahuang11** [comment]
Thanks for creating this PR.

> While this PR is not still sufficient to work around https://github.com/holoviz/holoviews/issues/6327, such revision must be required at least.

Can you elaborate a bit on this? What else is needed?

**Comment by hoxbro** [comment]
Currently, tests are failing because of your changes. Some seem trivial fixes (moving order around), while others do not. 

Making it so the tests pass will be the next step.

**Comment by hoxbro** [comment]
You are only running the `core-test`; try running the full test suite with `pixi run -e test-312 test-unit`.

**Comment by hoxbro** [comment]
Yes, they should be able to run on MacOS, but it seems like a bad file. Try `rm -rf .pixi pixi.lock` and then `pixi run` again. 

Are you running on an ARM Mac? Or is it an Intel?

**Pull request closed without merging**
