### PR TITLE
Support spatialpandas DaskGeoDataFrame

### PR DESCRIPTION
**Pull request by philippjfr**
Adds support for DaskGeoDataFrame to the SpatialpandasInterface.

- [x] Implements https://github.com/holoviz/holoviews/issues/4234
- [x] Add tests
- [x] Ensure all methods are handled

### CODE REVIEW

**Review by jbednar — COMMENTED** [review]
Looks straightforward, thanks! I'll test it out.

**Comment by jbednar** [comment]
Seems to work, but only if I add `, datatype=["spatialpandas"]`. Any chance that the datatype can be detected automatically? Otherwise I think a lot of people will just assume it doesn't work.

**Comment by philippjfr** [comment]
Of course but this isn't yet particularly close to being mergable.

**Comment by jlstevens** [comment]
This screenshot demonstrates an issue with spatial pandas support that I hope this PR can help address:

image

**Comment by jlstevens** [comment]
For what it is worth, I see the same problem as shown in the screenshot above when converting to geopandas.

**Comment by jbednar** [comment]
- [ ] See issue raised at https://github.com/holoviz/spatialpandas/issues/53 ; may need to be addressed here.

**Pull request merged**
